<?php

use Laravel\Fortify\Features;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Locked;
use Livewire\Attributes\On;
use Livewire\Attributes\Title;
use Livewire\Component;

new #[Layout('layouts.auth')] #[Title('Secure your account')] class extends Component {
    #[Locked]
    public bool $canManageTwoFactor;

    #[Locked]
    public bool $requiresConfirmation;

    public bool $twoFactorEnabled = false;

    #[Locked]
    public bool $canManagePasskeys;

    public int $passkeyCount = 0;

    public function mount(): void
    {
        $this->canManageTwoFactor = Features::canManageTwoFactorAuthentication();
        $this->requiresConfirmation = Features::optionEnabled(Features::twoFactorAuthentication(), 'confirm');
        $this->twoFactorEnabled = auth()->user()->hasEnabledTwoFactorAuthentication();

        $this->canManagePasskeys = Features::canManagePasskeys();
        $this->loadPasskeys();

        if ($this->isSecured()) {
            $this->redirect(route('onboarding.profile'), navigate: true);
        }
    }

    public function loadPasskeys(): void
    {
        $this->passkeyCount = auth()->user()->passkeys()->count();

        if ($this->isSecured()) {
            $this->redirect(route('onboarding.profile'), navigate: true);
        }
    }

    #[On('two-factor-enabled')]
    public function onTwoFactorEnabled(): void
    {
        $this->twoFactorEnabled = true;

        $this->redirect(route('onboarding.profile'), navigate: true);
    }

    private function isSecured(): bool
    {
        return $this->twoFactorEnabled || $this->passkeyCount > 0;
    }
}; ?>

<div class="flex flex-col gap-6">
    <div class="flex flex-col items-center gap-2 text-center">
        <flux:icon.shield-check class="size-10 text-blue-600 dark:text-blue-400" />
        <flux:heading size="lg">{{ __('Secure your account') }}</flux:heading>
        <flux:text>
            {{ __('We want to ensure the privacy of everyone in this family tree. Before continuing, please set up two-factor authentication or a passkey.') }}
        </flux:text>
        <flux:text>
            {{ __('There is personal information on this site. The only users on this site are family members.') }}
        </flux:text>
    </div>

    @if ($canManageTwoFactor)
        <section class="rounded-lg border border-zinc-200 p-4 dark:border-zinc-700">
            <flux:heading size="sm">{{ __('Two-factor authentication') }}</flux:heading>
            <flux:text class="mt-1">
                {{ __('You\'ll be prompted for a secure, random pin during login, generated by an authenticator app on your phone.') }}
            </flux:text>

            <div class="mt-4">
                <flux:modal.trigger name="two-factor-setup-modal">
                    <flux:button variant="primary" wire:click="$dispatch('start-two-factor-setup')">
                        {{ __('Set up 2FA') }}
                    </flux:button>
                </flux:modal.trigger>
                <livewire:pages::settings.two-factor-setup-modal :requires-confirmation="$requiresConfirmation" />
            </div>
        </section>
    @endif

    @if ($canManagePasskeys)
        <section class="rounded-lg border border-zinc-200 p-4 dark:border-zinc-700">
            <flux:heading size="sm">{{ __('Passkey') }}</flux:heading>
            <flux:text class="mt-1">
                {{ __('Sign in with your device\'s built-in authentication — fingerprint, face, or security key.') }}
            </flux:text>

            <div class="mt-4">
                <x-passkey-registration />
            </div>
        </section>
    @endif

    <flux:text class="text-center text-xs text-zinc-500">
        {{ __('This is required for every account — there\'s no skipping it.') }}
    </flux:text>
</div>
